# -*- coding: utf-8 -*-
"""formattingLogMessages.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZDJPfov-qy_OVgrO3BKyLcgmZDkrEVVX
"""

import logging

def customLoggerFormat():
  logger = logging.getLogger("customLogger")
  logger.setLevel(logging.DEBUG)

  fileHandler = logging.FileHandler('customApp.log')
  consoleHandler = logging.StreamHandler()

  fileFormatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
  consoleFormatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')

  fileHandler.setFormatter(fileFormatter)
  consoleHandler.setFormatter(consoleFormatter)

  logger.addHandler(fileHandler)
  logger.addHandler(consoleHandler)

  logger.debug('This is a debug message')
  logger.info('This is an info message')
  logger.warning('This is a warning message')
  logger.error('This is an error message')
  logger.critical('This is a critical message')

customLoggerFormat()

import logging

def customLoggerFormat():
  logger = logging.getLogger("customLogger")
  logger.setLevel(logging.DEBUG)

  fileHandler = logging.FileHandler('customApp.log')
  consoleHandler = logging.StreamHandler()

  formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
  fileHandler.setFormatter(formatter)
  consoleHandler.setFormatter(formatter)

  logger.addHandler(fileHandler)
  logger.addHandler(consoleHandler)

  logger.debug('This is a debug message')
  logger.info('This is an info message')
  logger.warning('This is a warning message')
  logger.error('This is an error message')
  logger.critical('This is a critical message')

customLoggerFormat()