# -*- coding: utf-8 -*-
"""Day3 Treasure Island.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x0ClG0kjKLvyGGFwrpd6kBVUtEEPKWYZ
"""

print('''
*******************************************************************************
          |                   |                  |                     |
 _________|________________.=""_;=.______________|_____________________|_______
|                   |  ,-"_,=""     `"=.|                  |
|___________________|__"=._o`"-._        `"=.______________|___________________
          |                `"=._o`"=._      _`"=._                     |
 _________|_____________________:=._o "=._."_.-="'"=.__________________|_______
|                   |    __.--" , ; `"=._o." ,-"""-._ ".   |
|___________________|_._"  ,. .` ` `` ,  `"-._"-._   ". '__|___________________
          |           |o`"=._` , "` `; .". ,  "-._"-._; ;              |
 _________|___________| ;`-.o`"=._; ." ` '`."\` . "-._ /_______________|_______
|                   | |o;    `"-.o`"=._``  '` " ,__.--o;   |
|___________________|_| ;     (#) `-.o `"=.`_.--"_o.-; ;___|___________________
____/______/______/___|o;._    "      `".o|o_.--"    ;o;____/______/______/____
/______/______/______/_"=._o--._        ; | ;        ; ;/______/______/______/_
____/______/______/______/__"=._o--._   ;o|o;     _._;o;____/______/______/____
/______/______/______/______/____"=._o._; | ;_.--"o.--"_/______/______/______/_
____/______/______/______/______/_____"=.o|o_.--""___/______/______/______/____
/______/______/______/______/______/______/______/______/______/______/_____ /
*******************************************************************************
''')
print("Welcome to Treasure Island.")
print("Your mission is to find the treasure.")
direction = str(input("Do you wanna go right or left ? "))
if direction == "left":
  #proceed
  stat = str(input("Do you wanna swim or wait "))
  if stat == "wait":
    #proceed
    door = str(input("Through which door you wanna go, red,blue, yelloe, or anything else "))
    if door == "blue":
      print("Eaten by beasts, Game Over! ")
    elif door == "red":
      print("Burned by fire, Game Over! ")
    elif door == "yellow":
      print("You win!")
    else:
      print("Game Over! ")

  else:
    print("Attacked by Trout, Game Over!")
else:
  print("Oops! You fell into a hole, Gameover! ")