# -*- coding: utf-8 -*-
"""Day4 Rock Paper Scissor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jjh3zJFOsmy7zFnxr8SDguNDOUzlp2VU
"""

import random
rock = '''
    _______
---'   ____)
      (_____)
      (_____)
      (____)
---.__(___)
'''
paper = '''
    _______
---'   ____)____
          ______)
          _______)
         _______)
---.__________)
'''
scissors = '''
    _______
---'   ____)____
          ______)
       __________)
      (____)
---.__(___)
'''

image_list = [rock, paper, scissors]

while(1):

  user_pick = int(input("What do you choose? Type 0 for Rock, 1 for Paper or 2 for Scissors or 3 exit.\n"))
  if user_pick == 3:
    break
  else:

    print(image_list[user_pick])

    computer_choice = random.randint(0, 3)
    print("Computer chose:")
    print(image_list[computer_choice])

    if user_pick > 3 or user_pick < 0:
      print("You typed an invalid number, you lose!")
    elif user_pick == 0 and computer_choice == 2:
      print("You win!")
    elif computer_choice == 0 and user_pick == 2:
      print("You lose")
    elif computer_choice > user_pick:
      print("You lose")
    elif user_pick > computer_choice:
      print("You win!")
    elif computer_choice == user_pick:
      print("Tie, Play Again!")

