# -*- coding: utf-8 -*-
"""Day5 Password Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PfAQy4d6ffgEIC6pMbOtSfvaKDph05yw
"""

import random

letters = [chr(i) for i in range(65, 91)] + [chr(i) for i in range(97, 123)]
#print(letters)
numbers = [str(i) for i in range(10)]
print(numbers)
special_characters = ['!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '-', '_', '=', '+', '[', ']', '{', '}', ';', ':', "'", '"', ',', '.', '<', '>', '/', '?', '|', '`', '~']
#print(special_characters)


print(" Welcome to Python Password Generator! I will help you in creating a safe and secure password for you. \n")
num_letters = int(input("How many letters do you want? \n "))
num_numbers = int(input("How many numbers do you want? \n "))
num_symbols = int(input("How many symbols do you want? \n "))

password = ""
password_strong = ""

password_list = []
for i in range(0,num_letters):
  password += random.choice(letters)
  password_list.append(random.choice(letters))
for i in range(0,num_numbers):
  password += random.choice(numbers)
  password_list.append(random.choice(numbers))
for i in range(0, num_symbols):
  password += random.choice(special_characters)
  password_list.append(random.choice(special_characters))

random.shuffle(password_list)



for i in password_list:
  password_strong += i

print("Your suggested for a good password is: ", password)
print(f"Your suggestion for a strong password is: {password_strong} ")