# -*- coding: utf-8 -*-
"""Day1 Band Name Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i3_YyIHKw_luZBpv7Je7PvH65H9uF7ry
"""

print("Hi, Welcome to Band Name Generator")
city_name = str(input("Which city did you grew up in ? \n"))
pet_name = str(input("What is the name of a pet ? \n"))
print("Your Band Name is ",city_name +" " + pet_name)