# -*- coding: utf-8 -*-
"""Day2 Tip Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FYXCQfiXpgyK1NF5G0eqTGk-kNZi8TWT
"""

print(" Hi, Welcome to the tip calculator! \n")
total = float(input(" What was the total bill? "))
tip_percent = float(input("\n How much tip(percent) would you like to give? 10,12 or 15? "))
count_people = int(input("\n How many people to split the bill? "))
individual_bill = total/float(count_people)
individual_tip = individual_bill * (tip_percent/100)
total_pay_each = individual_tip + individual_bill
print(" \n Each person should pay: ",total_pay_each)